"""Add mutual rating

Revision ID: 29bee308f713
Revises: 3c58cc47241d
Create Date: 2026-07-19 06:10:27.169757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bee308f713'
down_revision: Union[str, None] = '3c58cc47241d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluacion', sa.Column('estrellas_taller', sa.Integer(), nullable=True))
    op.add_column('evaluacion', sa.Column('comentario_taller', sa.Text(), nullable=True))
    op.alter_column('evaluacion', 'estrellas',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluacion', 'estrellas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('evaluacion', 'comentario_taller')
    op.drop_column('evaluacion', 'estrellas_taller')
    # ### end Alembic commands ###
