"""Add mantenimiento table

Revision ID: 3c58cc47241d
Revises: a1b2c3d40014
Create Date: 2026-07-19 03:08:04.337784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c58cc47241d'
down_revision: Union[str, None] = 'a1b2c3d40014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ubicacion_tecnico_asig_time', table_name='ubicacion_tecnico')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ubicacion_tecnico_asig_time', 'ubicacion_tecnico', ['id_asignacion', 'created_at'], unique=False)
    # ### end Alembic commands ###
