"""Add taller_favorito

Revision ID: 4ab07624e743
Revises: 29bee308f713
Create Date: 2026-07-19 08:12:51.290758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab07624e743'
down_revision: Union[str, None] = '29bee308f713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taller_favorito',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_favorito'),
    sa.UniqueConstraint('id_usuario', 'id_taller', name='uq_usuario_taller_favorito')
    )
    op.create_index(op.f('ix_taller_favorito_id_favorito'), 'taller_favorito', ['id_favorito'], unique=False)
    op.create_index(op.f('ix_taller_favorito_id_taller'), 'taller_favorito', ['id_taller'], unique=False)
    op.create_index(op.f('ix_taller_favorito_id_usuario'), 'taller_favorito', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taller_favorito_id_usuario'), table_name='taller_favorito')
    op.drop_index(op.f('ix_taller_favorito_id_taller'), table_name='taller_favorito')
    op.drop_index(op.f('ix_taller_favorito_id_favorito'), table_name='taller_favorito')
    op.drop_table('taller_favorito')
    # ### end Alembic commands ###
